# fly.toml app configuration file generated for htmlsky on 2024-06-08T16:01:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'htmlsky'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.22.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
